export const ADD_TODO = "ADD_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const REMOVE_COMPLETED_TODOS = "REMOVE_COMPLETED_TODOS"
export const API_URL = "http://localhost:5000/todos"
